export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: "realms" | "gates" | "streaks" | "practices" | "special";
  rarity: "common" | "rare" | "epic" | "legendary";
  unlockCondition: {
    type: "realms_explored" | "gates_completed" | "check_in_streak" | "days_active" | "ai_conversations" | "special";
    value: number;
  };
  color: string;
}

export const BADGES_DATA: Badge[] = [
  // Realms Badges
  {
    id: "realm_explorer_1",
    name: "First Steps",
    description: "Explore your first Realm",
    icon: "🌟",
    category: "realms",
    rarity: "common",
    unlockCondition: { type: "realms_explored", value: 1 },
    color: "#FFD700",
  },
  {
    id: "realm_explorer_10",
    name: "Realm Seeker",
    description: "Explore 10 Realms",
    icon: "🔮",
    category: "realms",
    rarity: "common",
    unlockCondition: { type: "realms_explored", value: 10 },
    color: "#FFD700",
  },
  {
    id: "realm_explorer_25",
    name: "Dimensional Traveler",
    description: "Explore 25 Realms",
    icon: "🌌",
    category: "realms",
    rarity: "rare",
    unlockCondition: { type: "realms_explored", value: 25 },
    color: "#9370DB",
  },
  {
    id: "realm_explorer_50",
    name: "Realm Master",
    description: "Explore 50 Realms",
    icon: "✨",
    category: "realms",
    rarity: "epic",
    unlockCondition: { type: "realms_explored", value: 50 },
    color: "#FF1493",
  },
  {
    id: "realm_explorer_100",
    name: "Cosmic Navigator",
    description: "Explore 100 Realms",
    icon: "🌠",
    category: "realms",
    rarity: "legendary",
    unlockCondition: { type: "realms_explored", value: 100 },
    color: "#FF4500",
  },
  {
    id: "realm_explorer_144",
    name: "Omniscient One",
    description: "Explore all 144 Realms",
    icon: "👁️",
    category: "realms",
    rarity: "legendary",
    unlockCondition: { type: "realms_explored", value: 144 },
    color: "#8B00FF",
  },

  // Gates Badges
  {
    id: "gate_warrior",
    name: "The Warrior",
    description: "Complete Gate 1",
    icon: "⚔️",
    category: "gates",
    rarity: "common",
    unlockCondition: { type: "gates_completed", value: 1 },
    color: "#DC143C",
  },
  {
    id: "gate_creator",
    name: "The Creator",
    description: "Complete Gate 2",
    icon: "🎨",
    category: "gates",
    rarity: "common",
    unlockCondition: { type: "gates_completed", value: 2 },
    color: "#FF6347",
  },
  {
    id: "gate_communicator",
    name: "The Communicator",
    description: "Complete Gate 3",
    icon: "📣",
    category: "gates",
    rarity: "rare",
    unlockCondition: { type: "gates_completed", value: 3 },
    color: "#FFD700",
  },
  {
    id: "gate_nurturer",
    name: "The Nurturer",
    description: "Complete Gate 4",
    icon: "🌙",
    category: "gates",
    rarity: "rare",
    unlockCondition: { type: "gates_completed", value: 4 },
    color: "#C0C0C0",
  },
  {
    id: "gate_dragon",
    name: "The Dragon",
    description: "Complete Gate 5",
    icon: "🐉",
    category: "gates",
    rarity: "epic",
    unlockCondition: { type: "gates_completed", value: 5 },
    color: "#FFD700",
  },
  {
    id: "gate_healer",
    name: "The Healer",
    description: "Complete Gate 6",
    icon: "💚",
    category: "gates",
    rarity: "epic",
    unlockCondition: { type: "gates_completed", value: 6 },
    color: "#32CD32",
  },
  {
    id: "gate_sovereign",
    name: "The Sovereign",
    description: "Complete Gate 11",
    icon: "👑",
    category: "gates",
    rarity: "legendary",
    unlockCondition: { type: "gates_completed", value: 11 },
    color: "#FFD700",
  },
  {
    id: "gate_mystic",
    name: "The Mystic",
    description: "Complete Gate 12",
    icon: "🔮",
    category: "gates",
    rarity: "legendary",
    unlockCondition: { type: "gates_completed", value: 12 },
    color: "#8B00FF",
  },

  // Streak Badges
  {
    id: "streak_3",
    name: "Committed",
    description: "3-day check-in streak",
    icon: "🔥",
    category: "streaks",
    rarity: "common",
    unlockCondition: { type: "check_in_streak", value: 3 },
    color: "#FF4500",
  },
  {
    id: "streak_7",
    name: "Dedicated",
    description: "7-day check-in streak",
    icon: "🔥🔥",
    category: "streaks",
    rarity: "rare",
    unlockCondition: { type: "check_in_streak", value: 7 },
    color: "#FF6347",
  },
  {
    id: "streak_30",
    name: "Disciplined",
    description: "30-day check-in streak",
    icon: "🔥🔥🔥",
    category: "streaks",
    rarity: "epic",
    unlockCondition: { type: "check_in_streak", value: 30 },
    color: "#FF1493",
  },
  {
    id: "streak_100",
    name: "Unstoppable",
    description: "100-day check-in streak",
    icon: "💎",
    category: "streaks",
    rarity: "legendary",
    unlockCondition: { type: "check_in_streak", value: 100 },
    color: "#00CED1",
  },

  // Days Active Badges
  {
    id: "days_7",
    name: "First Week",
    description: "7 days on your journey",
    icon: "🌱",
    category: "practices",
    rarity: "common",
    unlockCondition: { type: "days_active", value: 7 },
    color: "#32CD32",
  },
  {
    id: "days_30",
    name: "First Moon",
    description: "30 days on your journey",
    icon: "🌙",
    category: "practices",
    rarity: "rare",
    unlockCondition: { type: "days_active", value: 30 },
    color: "#C0C0C0",
  },
  {
    id: "days_90",
    name: "Seasonal Shift",
    description: "90 days on your journey",
    icon: "🍂",
    category: "practices",
    rarity: "epic",
    unlockCondition: { type: "days_active", value: 90 },
    color: "#FF8C00",
  },
  {
    id: "days_365",
    name: "Solar Return",
    description: "365 days on your journey",
    icon: "☀️",
    category: "practices",
    rarity: "legendary",
    unlockCondition: { type: "days_active", value: 365 },
    color: "#FFD700",
  },

  // AI Conversation Badges
  {
    id: "ai_chat_10",
    name: "Curious Mind",
    description: "10 AI conversations",
    icon: "💬",
    category: "practices",
    rarity: "common",
    unlockCondition: { type: "ai_conversations", value: 10 },
    color: "#1E90FF",
  },
  {
    id: "ai_chat_50",
    name: "Deep Seeker",
    description: "50 AI conversations",
    icon: "🧠",
    category: "practices",
    rarity: "rare",
    unlockCondition: { type: "ai_conversations", value: 50 },
    color: "#9370DB",
  },
  {
    id: "ai_chat_100",
    name: "Wisdom Seeker",
    description: "100 AI conversations",
    icon: "🦉",
    category: "practices",
    rarity: "epic",
    unlockCondition: { type: "ai_conversations", value: 100 },
    color: "#8B4513",
  },

  // Special Badges
  {
    id: "special_birth_data",
    name: "Star Child",
    description: "Enter your birth data",
    icon: "⭐",
    category: "special",
    rarity: "rare",
    unlockCondition: { type: "special", value: 1 },
    color: "#FFD700",
  },
  {
    id: "special_purple_flame",
    name: "Purple Flame",
    description: "Integrate your first shadow",
    icon: "🔥",
    category: "special",
    rarity: "epic",
    unlockCondition: { type: "special", value: 1 },
    color: "#8B00FF",
  },
  {
    id: "special_alchemist",
    name: "The Alchemist",
    description: "Complete the Alchemical Marriage",
    icon: "⚗️",
    category: "special",
    rarity: "legendary",
    unlockCondition: { type: "special", value: 1 },
    color: "#FFD700",
  },
];
