// 144 Realms of The 33rd House
// Each Gate contains 12 Realms (12 Gates × 12 Realms = 144)

export interface Realm {
  id: number;
  name: string;
  gate: number;
  gateName: string;
  zodiac: string;
  element: string;
  planet: string;
  archetype: string;
  shadow: string;
  crystal: string;
  plant: string;
  incense: string;
  mantra: string;
  color: string;
  description: string;
}

export const REALMS_DATA: Realm[] = [
  // Gate 0: The Threshold (Sagittarius) - Realms 1-12
  {
    id: 1,
    name: "The Awakening Call",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Clear Quartz",
    plant: "Sage",
    incense: "Frankincense",
    mantra: "I am ready to begin",
    color: "White",
    description: "The first step across the threshold. The moment of recognition that a journey awaits.",
  },
  {
    id: 2,
    name: "The Sacred Pause",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Selenite",
    plant: "White Sage",
    incense: "Sandalwood",
    mantra: "I pause and listen",
    color: "Silver",
    description: "The space between worlds. Learning to wait at the threshold with intention.",
  },
  {
    id: 3,
    name: "The First Vision",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Amethyst",
    plant: "Mugwort",
    incense: "Myrrh",
    mantra: "I see the path ahead",
    color: "Purple",
    description: "The glimpse of what lies beyond. The first vision of the journey to come.",
  },
  {
    id: 4,
    name: "The Commitment",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Black Tourmaline",
    plant: "Rosemary",
    incense: "Cedar",
    mantra: "I commit to the path",
    color: "Deep Blue",
    description: "The moment of decision. Choosing to cross the threshold with full awareness.",
  },
  {
    id: 5,
    name: "The Sacred Contract",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Lapis Lazuli",
    plant: "Lavender",
    incense: "Copal",
    mantra: "I honor my soul's agreement",
    color: "Indigo",
    description: "The soul agreement. Recognizing the contract made before incarnation.",
  },
  {
    id: 6,
    name: "The Release",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Smoky Quartz",
    plant: "Rue",
    incense: "Palo Santo",
    mantra: "I release what no longer serves",
    color: "Gray",
    description: "Letting go of the old world. Releasing attachments before crossing.",
  },
  {
    id: 7,
    name: "The Blessing",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Rose Quartz",
    plant: "Rose",
    incense: "Rose",
    mantra: "I am blessed and protected",
    color: "Pink",
    description: "Receiving the blessing of the ancestors. Protection for the journey ahead.",
  },
  {
    id: 8,
    name: "The Initiation",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Obsidian",
    plant: "Yarrow",
    incense: "Dragon's Blood",
    mantra: "I am initiated into the mysteries",
    color: "Black",
    description: "The formal initiation. Crossing the threshold with ceremony and intention.",
  },
  {
    id: 9,
    name: "The New Identity",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Citrine",
    plant: "St. John's Wort",
    incense: "Benzoin",
    mantra: "I embrace my new self",
    color: "Yellow",
    description: "Taking on the new identity. Becoming the practitioner, the initiate.",
  },
  {
    id: 10,
    name: "The First Step",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Carnelian",
    plant: "Cinnamon",
    incense: "Cinnamon",
    mantra: "I take the first step",
    color: "Orange",
    description: "The actual crossing. The first step into the new world.",
  },
  {
    id: 11,
    name: "The Point of No Return",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Red Jasper",
    plant: "Ginger",
    incense: "Clove",
    mantra: "I cannot go back",
    color: "Red",
    description: "The moment when return is no longer possible. Full commitment to the path.",
  },
  {
    id: 12,
    name: "The New World",
    gate: 0,
    gateName: "The Threshold",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Seeker",
    shadow: "The Wanderer",
    crystal: "Fire Agate",
    plant: "Bay Laurel",
    incense: "Juniper",
    mantra: "I have arrived in the new world",
    color: "Gold",
    description: "Arrival in the new realm. The threshold has been crossed completely.",
  },

  // Gate 1: The Warrior (Aries) - Realms 13-24
  {
    id: 13,
    name: "The Call to Arms",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Red Jasper",
    plant: "Nettle",
    incense: "Dragon's Blood",
    mantra: "I am a warrior of light",
    color: "Red",
    description: "The awakening of the warrior spirit. Recognizing the battles ahead.",
  },
  {
    id: 14,
    name: "The Sword of Truth",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Bloodstone",
    plant: "Thistle",
    incense: "Tobacco",
    mantra: "I wield truth as my weapon",
    color: "Crimson",
    description: "Claiming the sword of truth. Learning to fight with integrity.",
  },
  {
    id: 15,
    name: "The Shield of Faith",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Hematite",
    plant: "Hawthorn",
    incense: "Pine",
    mantra: "I am protected by faith",
    color: "Steel Gray",
    description: "Building the shield of protection. Faith as armor against darkness.",
  },
  {
    id: 16,
    name: "The Battle Within",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Garnet",
    plant: "Cayenne",
    incense: "Black Pepper",
    mantra: "I conquer my inner demons",
    color: "Dark Red",
    description: "The internal battle. Fighting the shadows within before facing external foes.",
  },
  {
    id: 17,
    name: "The Courage Test",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Tiger's Eye",
    plant: "Ginger",
    incense: "Cinnamon",
    mantra: "I am courageous",
    color: "Amber",
    description: "The test of courage. Facing fear and choosing to act anyway.",
  },
  {
    id: 18,
    name: "The Warrior's Code",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Carnelian",
    plant: "Basil",
    incense: "Ginger",
    mantra: "I honor the warrior's code",
    color: "Orange-Red",
    description: "Learning the code of honor. The warrior's path is one of discipline.",
  },
  {
    id: 19,
    name: "The First Victory",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Ruby",
    plant: "Chili Pepper",
    incense: "Clove",
    mantra: "I celebrate my victories",
    color: "Bright Red",
    description: "The first taste of victory. Learning to honor wins without arrogance.",
  },
  {
    id: 20,
    name: "The Wound",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Bloodstone",
    plant: "Yarrow",
    incense: "Myrrh",
    mantra: "My wounds make me stronger",
    color: "Deep Red",
    description: "Receiving the warrior's wound. Every warrior is marked by battle.",
  },
  {
    id: 21,
    name: "The Healing",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Red Calcite",
    plant: "Comfrey",
    incense: "Frankincense",
    mantra: "I heal and return stronger",
    color: "Rose Red",
    description: "Learning to heal wounds. The warrior must know when to rest.",
  },
  {
    id: 22,
    name: "The Return to Battle",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Fire Opal",
    plant: "Horseradish",
    incense: "Dragon's Blood",
    mantra: "I return to the fight",
    color: "Flame Red",
    description: "Rising again after defeat. The true warrior never stays down.",
  },
  {
    id: 23,
    name: "The Mastery",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Red Spinel",
    plant: "Allspice",
    incense: "Tobacco",
    mantra: "I am a master warrior",
    color: "Scarlet",
    description: "Achieving mastery of the warrior arts. Skill, discipline, and power united.",
  },
  {
    id: 24,
    name: "The Peaceful Warrior",
    gate: 1,
    gateName: "The Warrior",
    zodiac: "Aries",
    element: "Fire",
    planet: "Mars",
    archetype: "The Warrior",
    shadow: "The Aggressor",
    crystal: "Red Aventurine",
    plant: "Red Clover",
    incense: "Sandalwood",
    mantra: "I am a warrior of peace",
    color: "Soft Red",
    description: "The paradox of the peaceful warrior. Strength without aggression.",
  },


  // Gate 2: The Builder (Taurus) - Realms 25-36
  {
    id: 25,
    name: "The Seed of Creation",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Clear Quartz",
    plant: "Dandelion",
    incense: "Frankincense",
    mantra: "I am a vessel for creation.",
    color: "Alabaster White",
    description: "The first spark of intention, a pure potential planted in the fertile soil of possibility before form takes hold.",
  },
  {
    id: 26,
    name: "The Grounding Summons",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Black Tourmaline",
    plant: "Vetiver",
    incense: "Cedarwood",
    mantra: "I answer the call to build.",
    color: "Rich Loam",
    description: "A deep resonance from the earth calls you to your life's work, a summons to bring a specific structure into being.",
  },
  {
    id: 27,
    name: "The Apprentice's Forge",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Pyrite",
    plant: "Rosemary",
    incense: "Sandalwood",
    mantra: "I patiently learn the sacred craft.",
    color: "Iron Gray",
    description: "Here, you patiently acquire the fundamental skills and knowledge, sharpening the tools needed for the great work ahead.",
  },
  {
    id: 28,
    name: "The Cornerstone's Placement",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Hematite",
    plant: "Thyme",
    incense: "Myrrh",
    mantra: "I lay a foundation of integrity.",
    color: "Terracotta",
    description: "The first deliberate act of creation, placing a single, perfect stone that will anchor and align all that is to come.",
  },
  {
    id: 29,
    name: "The Unyielding Stone",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Obsidian",
    plant: "Hawthorn",
    incense: "Dragon's Blood",
    mantra: "I persist through every challenge.",
    color: "Basalt Black",
    description: "A trial of resolve appears as an immovable obstacle, demanding a new level of ingenuity and unwavering patience to proceed.",
  },
  {
    id: 30,
    name: "The Shifting Blueprint",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Smoky Quartz",
    plant: "Mullein",
    incense: "Patchouli",
    mantra: "I adapt my vision with wisdom.",
    color: "Slate Blue",
    description: "The initial plans falter against unforeseen complexities, forcing a difficult but necessary evolution of the original design.",
  },
  {
    id: 31,
    name: "The Gilded Cage",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Citrine",
    plant: "Burdock",
    incense: "Amber",
    mantra: "I release the fear of scarcity.",
    color: "Fool's Gold",
    description: "The shadow of the Hoarder emerges, tempting you to cling to what you have built, to value possession over purpose.",
  },
  {
    id: 32,
    name: "The Empty Treasury",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Rhodonite",
    plant: "Angelica",
    incense: "Copal",
    mantra: "My worth is not what I own.",
    color: "Dusty Rose",
    description: "In a moment of crisis, you confront the poverty of a spirit that only accumulates, realizing that true wealth is in the act of creation itself.",
  },
  {
    id: 33,
    name: "The Mason's Gift",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Green Aventurine",
    plant: "Alfalfa",
    incense: "Benzoin",
    mantra: "I build to give, not to keep.",
    color: "Jade Green",
    description: "A breakthrough occurs as you learn to release your creations into the world, finding joy in their utility and beauty for others.",
  },
  {
    id: 34,
    name: "The Living Structure",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Moss Agate",
    plant: "Oakmoss",
    incense: "Pine",
    mantra: "My creations are alive with purpose.",
    color: "Forest Green",
    description: "Your work takes on a life of its own, a breathing structure that serves a purpose far beyond your own ego or desire for ownership.",
  },
  {
    id: 35,
    name: "The Master's Hand",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Emerald",
    plant: "Patchouli",
    incense: "Rose",
    mantra: "I create with effortless mastery.",
    color: "Emerald Green",
    description: "Having integrated the lessons of patience and release, your hands now move with the effortless grace of a master craftsman.",
  },
  {
    id: 36,
    name: "The Silent Cathedral",
    gate: 2,
    gateName: "The Builder",
    zodiac: "Taurus",
    element: "Earth",
    planet: "Venus",
    archetype: "The Builder",
    shadow: "The Hoarder",
    crystal: "Diamond",
    plant: "Orchid",
    incense: "Opoponax",
    mantra: "I am a pillar of creation.",
    color: "Luminous Pearl",
    description: "Your final creation stands not as a monument to self, but as a sacred space, a testament to the enduring power of building with love.",
  },

  // Gate 3: The Messenger (Gemini) - Realms 37-48
  {
    id: 37,
    name: "The Whispering Scroll",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Angelite",
    plant: "Lavender",
    incense: "Frankincense",
    mantra: "I listen for the universe's hidden messages.",
    color: "Periwinkle",
    description: "A sudden insight or a whispered word awakens the soul to the power of sacred communication.",
  },
  {
    id: 38,
    name: "The Silver Quill",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Lapis Lazuli",
    plant: "Anise",
    incense: "Sandalwood",
    mantra: "I am ready to speak my authentic truth.",
    color: "Cobalt Blue",
    description: "The call is received to become a conduit for truth, to write and speak with divine purpose.",
  },
  {
    id: 39,
    name: "The Echoing Library",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Sodalite",
    plant: "Peppermint",
    incense: "Mastic",
    mantra: "I study the sacred languages of creation.",
    color: "Indigo",
    description: "Here, one learns the foundational patterns of sacred language and the structure of universal truth.",
  },
  {
    id: 40,
    name: "The Harmonic Reed",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Blue Lace Agate",
    plant: "Dill",
    incense: "Benzoin",
    mantra: "I build my voice upon a foundation of clarity.",
    color: "Sky Blue",
    description: "The voice is tempered and strengthened, learning to resonate with clarity and coherence.",
  },
  {
    id: 41,
    name: "The Maze of Mirrors",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Aquamarine",
    plant: "Caraway",
    incense: "Copal",
    mantra: "I navigate through illusion with a clear voice.",
    color: "Teal",
    description: "The first great trial: to speak truth in a world of distortion and half-truths, without losing one's way.",
  },
  {
    id: 42,
    name: "The Silent Vow",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Kyanite",
    plant: "Fennel",
    incense: "Myrrh",
    mantra: "I hold the power of silence as well as speech.",
    color: "Slate Gray",
    description: "The challenge is to know when not to speak, to honor the power of silence and sacred secrets.",
  },
  {
    id: 43,
    name: "The Serpent's Tongue",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Amazonite",
    plant: "Mandrake",
    incense: "Dragon's Blood",
    mantra: "I face the temptation to twist words for gain.",
    color: "Olive Green",
    description: "The shadow of the Deceiver emerges, tempting the messenger to use their gift for manipulation and personal power.",
  },
  {
    id: 44,
    name: "The Shattered Word",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Clear Quartz",
    plant: "Valerian",
    incense: "Storax",
    mantra: "I reclaim my voice from the grip of falsehood.",
    color: "Charcoal",
    description: "In the crisis of deception, the voice is broken, and the messenger must find the path back to integrity.",
  },
  {
    id: 45,
    name: "The Unspoken Truth",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Celestite",
    plant: "Vervain",
    incense: "Galbanum",
    mantra: "I now speak the truth that was once unspeakable.",
    color: "Lavender",
    description: "A breakthrough occurs as the messenger finds the courage to voice a difficult or long-hidden truth.",
  },
  {
    id: 46,
    name: "The Bridge of Voices",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Turquoise",
    plant: "Lemon Verbena",
    incense: "Palo Santo",
    mantra: "My words now connect and unite different worlds.",
    color: "Cyan",
    description: "The messenger learns to bridge disparate worlds, translating between languages, cultures, and realms of consciousness.",
  },
  {
    id: 47,
    name: "The Diamond Scribe",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Herkimer Diamond",
    plant: "Mugwort",
    incense: "Amber",
    mantra: "I inscribe eternal truths with perfect clarity.",
    color: "White",
    description: "Mastery is achieved as the messenger can now channel and record universal truths with flawless precision.",
  },
  {
    id: 48,
    name: "The Resonant Word",
    gate: 3,
    gateName: "The Messenger",
    zodiac: "Gemini",
    element: "Air",
    planet: "Mercury",
    archetype: "The Messenger",
    shadow: "The Deceiver",
    crystal: "Danburite",
    plant: "Gotu Kola",
    incense: "Opoponax",
    mantra: "My every word now resonates with divine will.",
    color: "Gold",
    description: "The messenger fully integrates their gift, and their every utterance is an act of co-creation with the divine.",
  },

  // Gate 4: The Nurturer (Cancer) - Realms 49-60
  {
    id: 49,
    name: "The Sheltering Cove",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Moonstone",
    plant: "Jasmine",
    incense: "Sandalwood",
    mantra: "I create a safe space within myself.",
    color: "Pearl White",
    description: "A gentle call to turn inward and find the quiet harbor of your own heart.",
  },
  {
    id: 50,
    name: "The Whispering Well",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Selenite",
    plant: "Willow",
    incense: "Myrrh",
    mantra: "I listen to the wisdom of my ancestors.",
    color: "Silver",
    description: "Ancient voices murmur from the deep, offering guidance and revealing the sacred feminine within.",
  },
  {
    id: 51,
    name: "The Moonlit Garden",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Rose Quartz",
    plant: "Motherwort",
    incense: "Rose",
    mantra: "I nurture myself with unconditional love.",
    color: "Pale Pink",
    description: "Learning to tend to your own emotional needs is the foundation of nurturing others.",
  },
  {
    id: 52,
    name: "The Sacred Hearth",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Carnelian",
    plant: "Chamomile",
    incense: "Chamomile",
    mantra: "I build a sanctuary of warmth and comfort.",
    color: "Warm Orange",
    description: "The art of creating a home, both within and without, that is a true refuge.",
  },
  {
    id: 53,
    name: "The Tide of Sorrows",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Aquamarine",
    plant: "Lemon Balm",
    incense: "Frankincense",
    mantra: "I allow my feelings to flow without judgment.",
    color: "Seafoam Green",
    description: "A challenge to embrace the full spectrum of emotions, even the painful ones, without being swept away.",
  },
  {
    id: 54,
    name: "The Empty Nest",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Pearl",
    plant: "Sage",
    incense: "Sage",
    mantra: "I release what no longer serves me.",
    color: "Dove Gray",
    description: "The difficult but necessary lesson of letting go and allowing others their own journey.",
  },
  {
    id: 55,
    name: "The Martyr's Burden",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Hematite",
    plant: "Mugwort",
    incense: "Dragon's Blood",
    mantra: "I honor my own needs as sacred.",
    color: "Deep Burgundy",
    description: "Confronting the shadow of self-sacrifice and the resentment that festers in its wake.",
  },
  {
    id: 56,
    name: "The Sunken Cathedral",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Black Tourmaline",
    plant: "Valerian",
    incense: "Copal",
    mantra: "I reclaim the lost parts of my soul.",
    color: "Midnight Blue",
    description: "A descent into the depths of the unconscious to heal ancestral wounds and reclaim buried power.",
  },
  {
    id: 57,
    name: "The Silver Chalice",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Angelite",
    plant: "Lavender",
    incense: "Lavender",
    mantra: "I am a vessel of divine love.",
    color: "Lavender",
    description: "A breakthrough of self-love and the realization that you are worthy of receiving as much as you give.",
  },
  {
    id: 58,
    name: "The River of Life",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Amazonite",
    plant: "Lotus",
    incense: "Lotus",
    mantra: "I flow with the currents of grace.",
    color: "Turquoise",
    description: "Finding your place in the great flow of life, giving and receiving in perfect harmony.",
  },
  {
    id: 59,
    name: "The Pearl of Great Price",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Rainbow Moonstone",
    plant: "Orris Root",
    incense: "Amber",
    mantra: "I am a radiant source of love.",
    color: "Iridescent White",
    description: "Mastery of the heart, where the love you give and the love you receive become one.",
  },
  {
    id: 60,
    name: "The Cosmic Ocean",
    gate: 4,
    gateName: "The Nurturer",
    zodiac: "Cancer",
    element: "Water",
    planet: "Moon",
    archetype: "The Nurturer",
    shadow: "The Martyr",
    crystal: "Larimar",
    plant: "Kava Kava",
    incense: "Nag Champa",
    mantra: "I am one with the universal mother.",
    color: "Deep Ocean Blue",
    description: "Integrating the archetype of the Nurturer, you become a source of unconditional love for all beings.",
  },

  // Gate 5: The Heart (Leo) - Realms 61-72
  {
    id: 61,
    name: "The Sunstone Citadel",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Sunstone",
    plant: "Sunflower",
    incense: "Frankincense",
    mantra: "I awaken to the radiant sun within.",
    color: "Gold",
    description: "The journey begins with the first light of inner dawn, awakening the call to heart-centered sovereignty.",
  },
  {
    id: 62,
    name: "The Ruby Ignition",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Ruby",
    plant: "Rosemary",
    incense: "Cinnamon",
    mantra: "I answer the call of my courageous heart.",
    color: "Ruby Red",
    description: "A spark of courage ignites, accepting the quest to lead with love and express the soul's fire.",
  },
  {
    id: 63,
    name: "The Golden Path",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Citrine",
    plant: "Calendula",
    incense: "Sandalwood",
    mantra: "I walk the path of authentic self-expression.",
    color: "Marigold",
    description: "The principles of creative sovereignty are learned, illuminating the way of the heart.",
  },
  {
    id: 64,
    name: "The Lion's Heart",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Tiger's Eye",
    plant: "St. John's Wort",
    incense: "Bergamot",
    mantra: "I embody the courage and strength of my heart.",
    color: "Amber",
    description: "The foundations of heart-centered leadership are established, building a throne of inner strength.",
  },
  {
    id: 65,
    name: "The Dragon's Fire",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Carnelian",
    plant: "Hawthorn",
    incense: "Dragon's Blood",
    mantra: "I face my challenges with a fiery, open heart.",
    color: "Scarlet",
    description: "The first great trial begins, a test of courage and the heart's capacity to transmute fear into love.",
  },
  {
    id: 66,
    name: "The Radiant Trial",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Pyrite",
    plant: "Cinnamon",
    incense: "Copal",
    mantra: "I shine my light brightly in the face of darkness.",
    color: "Bronze",
    description: "A challenge to remain radiant and generous of spirit when confronted with scarcity and doubt.",
  },
  {
    id: 67,
    name: "The Shadow Throne",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Garnet",
    plant: "Rue",
    incense: "Myrrh",
    mantra: "I confront the temptation of power without love.",
    color: "Crimson",
    description: "The crisis point: a confrontation with the Tyrant shadow, the desire to control and dominate rather than empower.",
  },
  {
    id: 68,
    name: "The Gilded Cage",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Red Jasper",
    plant: "Nettle",
    incense: "Galbanum",
    mantra: "I release the need to rule through fear.",
    color: "Rust",
    description: "The heart is tested by the allure of a gilded cage, the illusion of safety in a closed and guarded heart.",
  },
  {
    id: 69,
    name: "The Heart's Liberation",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Rose Quartz",
    plant: "Motherwort",
    incense: "Rose",
    mantra: "I choose love and liberate my sovereign heart.",
    color: "Rose Gold",
    description: "The breakthrough: the Tyrant is dethroned by compassion, and the heart is liberated into its true power.",
  },
  {
    id: 70,
    name: "The Solar Flare",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Fire Opal",
    plant: "Angelica",
    incense: "Jasmine",
    mantra: "My creative power flows from an open heart.",
    color: "Tangerine",
    description: "A brilliant burst of creative energy is unleashed as the solar principle is fully embraced.",
  },
  {
    id: 71,
    name: "The Emerald Scepter",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Emerald",
    plant: "Basil",
    incense: "Lotus",
    mantra: "I rule my inner kingdom with love and wisdom.",
    color: "Emerald Green",
    description: "Mastery is achieved. The King/Queen now wields the scepter of the heart, a symbol of loving authority.",
  },
  {
    id: 72,
    name: "The Kingdom of Light",
    gate: 5,
    gateName: "The Heart",
    zodiac: "Leo",
    element: "Fire",
    planet: "Sun",
    archetype: "The King/Queen",
    shadow: "The Tyrant",
    crystal: "Diamond",
    plant: "Frankincense",
    incense: "Amber",
    mantra: "I am a radiant sun, a source of warmth and life.",
    color: "Diamond White",
    description: "Integration is complete. The heart becomes a star, a source of light and warmth for all beings in the kingdom.",
  },

  // Gate 6: The Healer (Virgo) - Realms 73-84
  {
    id: 73,
    name: "The Seed of Compassion",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Moss Agate",
    plant: "Yarrow",
    incense: "Cedarwood",
    mantra: "I open my heart to the call of healing.",
    color: "Spring Green",
    description: "A gentle stirring within, the first recognition of the universal wound and the desire to mend it.",
  },
  {
    id: 74,
    name: "The Whispering Woods",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Petrified Wood",
    plant: "Mullein",
    incense: "Pine",
    mantra: "I listen to the wisdom of the ancient earth.",
    color: "Forest Green",
    description: "Drawn to the quiet wisdom of nature, the nascent healer learns to listen to the subtle language of the earth.",
  },
  {
    id: 75,
    name: "The Apothecary's Garden",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Green Aventurine",
    plant: "Calendula",
    incense: "Lavender",
    mantra: "I learn the sacred properties of the green nation.",
    color: "Marigold",
    description: "A place of study and cultivation, where the healer learns the properties of herbs and the art of medicine making.",
  },
  {
    id: 76,
    name: "The Alchemist's Crucible",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Serpentine",
    plant: "St. John's Wort",
    incense: "Frankincense",
    mantra: "I transmute poison into medicine through careful discernment.",
    color: "Brass",
    description: "The art of discernment is honed here, learning to separate the poison from the panacea and to understand the delicate balance of healing.",
  },
  {
    id: 77,
    name: "The Fevered Grove",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Bloodstone",
    plant: "Echinacea",
    incense: "Myrrh",
    mantra: "I face the dis-ease within myself and the world.",
    color: "Crimson",
    description: "The first true test, a rampant illness sweeps through the land, challenging the healer's knowledge and resolve.",
  },
  {
    id: 78,
    name: "The Barren Field",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Smoky Quartz",
    plant: "Nettle",
    incense: "Copal",
    mantra: "I find nourishment even in the most desolate places.",
    color: "Dusty Brown",
    description: "A challenge of depletion and scarcity, where the healer must find a way to bring life back to a blighted land.",
  },
  {
    id: 79,
    name: "The Wounded Healer's Cave",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Apache Tear",
    plant: "Mugwort",
    incense: "Dragon's Blood",
    mantra: "I embrace my own wounds as a source of empathy.",
    color: "Charcoal Gray",
    description: "The healer must confront their own unhealed wounds, realizing that true healing comes from a place of shared vulnerability.",
  },
  {
    id: 80,
    name: "The Shadow of Perfection",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Black Tourmaline",
    plant: "Belladonna",
    incense: "Patchouli",
    mantra: "I release the need to fix everything and everyone.",
    color: "Midnight Blue",
    description: "The temptation to become a savior, to fix everything, leads to burnout and the realization that some things cannot be fixed, only witnessed.",
  },
  {
    id: 81,
    name: "The Spring of Renewal",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Clear Quartz",
    plant: "Comfrey",
    incense: "Sandalwood",
    mantra: "I am a clear channel for healing energy to flow.",
    color: "Aqua",
    description: "After confronting the shadow, the healer finds a source of pure, inexhaustible energy, a breakthrough of clarity and purpose.",
  },
  {
    id: 82,
    name: "The Weavers of Light",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Selenite",
    plant: "Angelica",
    incense: "Jasmine",
    mantra: "I weave wholeness from the threads of brokenness.",
    color: "Ivory",
    description: "The healer learns to mend not just the body, but the spirit, weaving together the fragmented parts of the self and the community.",
  },
  {
    id: 83,
    name: "The Garden of Service",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Jade",
    plant: "Rosemary",
    incense: "Rose",
    mantra: "I offer my gifts in humble and dedicated service.",
    color: "Jade Green",
    description: "Having mastered the art, the healer now tends to the community, offering their wisdom and compassion freely and without attachment to outcome.",
  },
  {
    id: 84,
    name: "The Silent Communion",
    gate: 6,
    gateName: "The Healer",
    zodiac: "Virgo",
    element: "Earth",
    planet: "Mercury",
    archetype: "The Healer",
    shadow: "The Wounded",
    crystal: "Amethyst",
    plant: "Holy Basil (Tulsi)",
    incense: "Spikenard",
    mantra: "I am one with the healing power of the universe.",
    color: "Violet",
    description: "The final integration, where the healer dissolves the boundary between self and other, becoming a living embodiment of the healing force of the cosmos.",
  },

  // Gate 7: The Lover (Libra) - Realms 85-96
  {
    id: 85,
    name: "The Mirror of Desire",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Rose Quartz",
    plant: "Rose",
    incense: "Rose",
    mantra: "I see myself in the beloved",
    color: "Blush Pink",
    description: "The first encounter with the mirror of desire. Recognizing that what you seek in another lives within you.",
  },
  {
    id: 86,
    name: "The Invitation",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Rhodonite",
    plant: "Jasmine",
    incense: "Ylang Ylang",
    mantra: "I open my heart without condition",
    color: "Soft Coral",
    description: "The sacred invitation to vulnerability. Opening the heart's gate without knowing what will enter.",
  },
  {
    id: 87,
    name: "The Dance of Polarity",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Rhodochrosite",
    plant: "Damiana",
    incense: "Sandalwood",
    mantra: "I embrace both giving and receiving",
    color: "Warm Rose",
    description: "Learning the eternal dance between masculine and feminine, giving and receiving, self and other.",
  },
  {
    id: 88,
    name: "The Garden of Devotion",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Green Aventurine",
    plant: "Lavender",
    incense: "Jasmine",
    mantra: "I tend the garden of my devotion",
    color: "Sage Green",
    description: "Cultivating devotion as a daily practice. Love is not a feeling but a garden that must be tended.",
  },
  {
    id: 89,
    name: "The Trial of Attachment",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Morganite",
    plant: "Passionflower",
    incense: "Patchouli",
    mantra: "I love without grasping",
    color: "Dusty Mauve",
    description: "The trial where love becomes possession. Learning to hold the beloved with open hands.",
  },
  {
    id: 90,
    name: "The Wound of Betrayal",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Apache Tear",
    plant: "Hawthorn Berry",
    incense: "Myrrh",
    mantra: "I forgive and remain open",
    color: "Deep Plum",
    description: "The inevitable wound of the heart. Betrayal as teacher, showing where trust was misplaced in the other instead of the self.",
  },
  {
    id: 91,
    name: "The Dark Night of the Heart",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Black Moonstone",
    plant: "Motherwort",
    incense: "Copal",
    mantra: "I find love in the darkness",
    color: "Midnight Blue",
    description: "The crisis of the lover. When all external love is stripped away and only the inner flame remains.",
  },
  {
    id: 92,
    name: "The Self-Marriage",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Kunzite",
    plant: "Hibiscus",
    incense: "Frankincense",
    mantra: "I am complete within myself",
    color: "Pearl White",
    description: "The sacred marriage within. Uniting the inner masculine and feminine into wholeness before seeking union outside.",
  },
  {
    id: 93,
    name: "The Tantric Fire",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Garnet",
    plant: "Cacao",
    incense: "Dragon's Blood",
    mantra: "I transmute desire into devotion",
    color: "Crimson",
    description: "The alchemical fire of sacred sexuality. Transmuting raw desire into spiritual fuel and creative power.",
  },
  {
    id: 94,
    name: "The Covenant of Equals",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Pink Tourmaline",
    plant: "Yarrow",
    incense: "Benzoin",
    mantra: "I honor the sacred in my partner",
    color: "Warm Gold",
    description: "The covenant between equals. True partnership built on mutual sovereignty, not need.",
  },
  {
    id: 95,
    name: "The Beauty of Impermanence",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Lepidolite",
    plant: "Cherry Blossom",
    incense: "Nag Champa",
    mantra: "I cherish what is fleeting",
    color: "Pale Lavender",
    description: "Mastering the art of loving what will pass. Finding beauty precisely because it is impermanent.",
  },
  {
    id: 96,
    name: "The Eternal Beloved",
    gate: 7,
    gateName: "The Lover",
    zodiac: "Libra",
    element: "Air",
    planet: "Venus",
    archetype: "The Lover",
    shadow: "The Obsessed",
    crystal: "Diamond",
    plant: "Lotus",
    incense: "Rose",
    mantra: "I am love itself",
    color: "Iridescent White",
    description: "The final realization of the lover's path. You are not seeking love — you are love. The beloved was always within.",
  },

  // Gate 8: The Transformer (Scorpio) - Realms 97-108
  {
    id: 97,
    name: "The Shattering Veil",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Black Obsidian",
    plant: "Black Cohosh",
    incense: "Myrrh",
    mantra: "I release what is no longer me.",
    color: "Midnight Blue",
    description: "A sudden crisis shatters the foundations of the known world, initiating the painful but necessary process of transformation.",
  },
  {
    id: 98,
    name: "The Serpent's Stir",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Red Jasper",
    plant: "Ginger",
    incense: "Cinnamon",
    mantra: "I awaken the dormant power within.",
    color: "Crimson",
    description: "The first flicker of kundalini energy stirs at the base of the spine, a potent call to a deeper, more primal consciousness.",
  },
  {
    id: 99,
    name: "The Alchemist's Pact",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Labradorite",
    plant: "Rosemary",
    incense: "Frankincense",
    mantra: "I commit to the great work of my soul.",
    color: "Iridescent Black",
    description: "A conscious agreement is made to engage with the shadow, turning leaden parts of the self into gold through intentional alchemy.",
  },
  {
    id: 100,
    name: "The Cauldron of Shadows",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Smoky Quartz",
    plant: "Bloodroot",
    incense: "Sandalwood",
    mantra: "I embrace the darkness to find the light.",
    color: "Charcoal Grey",
    description: "This realm is a vessel for confronting and integrating the rejected aspects of the self, brewing a potion of wholeness.",
  },
  {
    id: 101,
    name: "The Descent into Silence",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Shungite",
    plant: "Cedar",
    incense: "Agarwood",
    mantra: "I listen to the wisdom in the stillness.",
    color: "Deep Violet",
    description: "A necessary journey inward, away from external noise, to face the raw, untamed wilderness of the psyche.",
  },
  {
    id: 102,
    name: "The Mirror of Souls",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Infinite Stone",
    plant: "Tulsi",
    incense: "Rose",
    mantra: "I see my true self in all things.",
    color: "Silver",
    description: "Relationships and encounters become mirrors, reflecting back the deepest truths and unresolved patterns for healing.",
  },
  {
    id: 103,
    name: "The Ego's Last Stand",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Bloodstone",
    plant: "Garlic",
    incense: "Nag Champa",
    mantra: "I surrender my will to a higher power.",
    color: "Maroon",
    description: "The constructed self fights for survival, a final, fiery test of attachment before the ultimate surrender.",
  },
  {
    id: 104,
    name: "The Dark Night's Embrace",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Malachite",
    plant: "Ashwagandha",
    incense: "Vanilla",
    mantra: "I trust the process of my undoing.",
    color: "Pitch Black",
    description: "A period of profound emptiness and dissolution, where the old identity completely dissolves to make way for the new.",
  },
  {
    id: 105,
    name: "The Phoenix Fire",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Sunstone",
    plant: "Cinnamon",
    incense: "Dragon's Blood",
    mantra: "I rise renewed from the ashes of my past.",
    color: "Gold",
    description: "From the depths of surrender, a powerful rebirth occurs. The soul emerges, purified and strengthened by the flames of transformation.",
  },
  {
    id: 106,
    name: "The Unveiling Light",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Selenite",
    plant: "Brahmi",
    incense: "Copal",
    mantra: "I see with clarity and profound insight.",
    color: "White Light",
    description: "The new consciousness dawns, bringing with it deep psychic power, clarity of vision, and an incorruptible connection to truth.",
  },
  {
    id: 107,
    name: "The Scar of Wisdom",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Apache Tear",
    plant: "Dandelion",
    incense: "Vetiver",
    mantra: "I honor the journey that shaped me.",
    color: "Gunmetal",
    description: "The wounds of the past are integrated not as damage, but as marks of resilience and sources of profound wisdom and empathy.",
  },
  {
    id: 108,
    name: "The Endless Becoming",
    gate: 8,
    gateName: "The Transformer",
    zodiac: "Scorpio",
    element: "Water",
    planet: "Pluto",
    archetype: "The Transformer",
    shadow: "The Destroyer",
    crystal: "Amethyst",
    plant: "Haritaki",
    incense: "Lotus",
    mantra: "I am a vessel for constant evolution.",
    color: "Royal Purple",
    description: "Transformation is not a destination, but a perpetual state of being. The soul embraces its nature as an ever-unfolding mystery.",
  },

  // Gate 9: The Sage (Sagittarius) - Realms 109-120
  {
    id: 109,
    name: "The Unspoken Question",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Lapis Lazuli",
    plant: "Sage",
    incense: "Frankincense",
    mantra: "I seek the truth that lies beyond the veil.",
    color: "Deep Indigo",
    description: "A persistent question echoes in the soul, sparking the quest for deeper meaning and understanding. The journey into the Sage's path begins not with an answer, but with a profound inquiry.",
  },
  {
    id: 110,
    name: "The Pilgrim's First Step",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Clear Quartz",
    plant: "Dandelion",
    incense: "Sandalwood",
    mantra: "I walk the path of knowledge with an open heart.",
    color: "Pale Gold",
    description: "The journey of a thousand miles begins with a single, intentional step. This realm marks the conscious commitment to the path of higher learning and philosophical exploration.",
  },
  {
    id: 111,
    name: "The Scholar's Lantern",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Sodalite",
    plant: "Rosemary",
    incense: "Cedarwood",
    mantra: "I illuminate my mind with the light of ancient wisdom.",
    color: "Royal Blue",
    description: "In the great library of the cosmos, the seeker finds the foundational texts and teachings. This is a time of diligent study and absorbing the wisdom of those who have walked the path before.",
  },
  {
    id: 112,
    name: "The Sacred Dialogue",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Blue Lace Agate",
    plant: "Anise",
    incense: "Copal",
    mantra: "I listen deeply and speak my truth with clarity.",
    color: "Sky Blue",
    description: "Knowledge is not merely consumed, but engaged with through dialogue and debate. Here, the seeker learns to articulate their understanding and listen to the perspectives of others.",
  },
  {
    id: 113,
    name: "The Paradox Grove",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Labradorite",
    plant: "Mugwort",
    incense: "Myrrh",
    mantra: "I embrace contradiction to find a higher synthesis.",
    color: "Forest Green",
    description: "The path to wisdom is filled with paradoxes that defy simple logic. This realm challenges the seeker to hold opposing truths in balance, expanding the mind beyond dualistic thinking.",
  },
  {
    id: 114,
    name: "The Arrow of Truth",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Turquoise",
    plant: "Clove",
    incense: "Dragon's Blood",
    mantra: "I aim my intention and speak with unwavering honesty.",
    color: "Teal",
    description: "The Sage's truth is like an arrow, shot with precision and purpose. This realm tests the seeker's courage to speak their truth, even when it is difficult or unpopular.",
  },
  {
    id: 115,
    name: "The Fortress of Dogma",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Smoky Quartz",
    plant: "Thistle",
    incense: "Benzoin",
    mantra: "I release the need to be right, embracing humility.",
    color: "Charcoal Gray",
    description: "The shadow of the Sage emerges as the Dogmatist, who clings to rigid beliefs. This realm is a confrontation with intellectual pride and the temptation to build walls of certainty.",
  },
  {
    id: 116,
    name: "The Echoes of Judgment",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Black Tourmaline",
    plant: "Nettle",
    incense: "Patchouli",
    mantra: "I observe my judgments without attachment.",
    color: "Ashen",
    description: "In the crisis of faith, the seeker must confront their own inner critic and the tendency to judge others. This is a purification by fire, burning away the dross of intellectual arrogance.",
  },
  {
    id: 117,
    name: "The Starfire Revelation",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Amethyst",
    plant: "Star Anise",
    incense: "Opoponax",
    mantra: "I am a vessel for divine inspiration and insight.",
    color: "Violet",
    description: "Having passed through the shadow, a breakthrough occurs as a flash of cosmic insight. The seeker directly experiences a truth that transcends books and doctrines.",
  },
  {
    id: 118,
    name: "The Weaving of Worlds",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Citrine",
    plant: "Saffron",
    incense: "Amber",
    mantra: "I integrate my knowledge into a unified whole.",
    color: "Marigold",
    description: "The breakthrough is followed by the patient work of integration. The Sage learns to weave together disparate threads of knowledge into a coherent and beautiful tapestry of wisdom.",
  },
  {
    id: 119,
    name: "The Fountain of Wisdom",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Topaz",
    plant: "Ginseng",
    incense: "Lotus",
    mantra: "I share my wisdom freely for the benefit of all.",
    color: "Goldenrod",
    description: "True mastery is not in hoarding knowledge, but in becoming a source for others. The Sage's wisdom now flows effortlessly, offering nourishment and guidance to all who seek it.",
  },
  {
    id: 120,
    name: "The Silent Transmission",
    gate: 9,
    gateName: "The Sage",
    zodiac: "Sagittarius",
    element: "Fire",
    planet: "Jupiter",
    archetype: "The Sage",
    shadow: "The Dogmatist",
    crystal: "Selenite",
    plant: "Sandalwood",
    incense: "Nag Champa",
    mantra: "I embody the wisdom that needs no words.",
    color: "White",
    description: "The highest teaching is transmitted not through words, but through presence. The Sage has become a living embodiment of the truth, and their very being radiates wisdom and peace.",
  },

  // Gate 10: The Master (Capricorn) - Realms 121-132
  {
    id: 121,
    name: "The Summit's Call",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Smoky Quartz",
    plant: "Mullein",
    incense: "Cedarwood",
    mantra: "I heed the call to my highest peak.",
    color: "Slate Gray",
    description: "A distant mountain peak appears in a dream, its summit calling you to begin the arduous journey of self-mastery. The path begins now.",
  },
  {
    id: 122,
    name: "The Elder's Map",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Black Tourmaline",
    plant: "Comfrey",
    incense: "Pine",
    mantra: "I accept the wisdom of those before me.",
    color: "Forest Green",
    description: "An ancient map, gifted by a mysterious elder, reveals the hidden paths and challenges of the mountain. Your inheritance is the accumulated wisdom of the ages.",
  },
  {
    id: 123,
    name: "The Foundation Stone",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Hematite",
    plant: "Rosemary",
    incense: "Sandalwood",
    mantra: "I build my legacy on a solid foundation.",
    color: "Earthen Brown",
    description: "You lay the first stone of your life's great work, understanding that true mastery is built with patience and discipline. Each action is a deliberate step.",
  },
  {
    id: 124,
    name: "The Discipline of Days",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Garnet",
    plant: "Sage",
    incense: "Frankincense",
    mantra: "I embrace the rhythm of daily practice.",
    color: "Deep Burgundy",
    description: "The rhythm of daily effort becomes a meditation, crystallizing your will into unwavering focus. Time itself becomes your greatest teacher.",
  },
  {
    id: 125,
    name: "The Mountain's Trial",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Malachite",
    plant: "Holly",
    incense: "Dragon's Blood",
    mantra: "I face my challenges with courage and resolve.",
    color: "Hunter Green",
    description: "The path steepens, and the first great trial appears as a fierce storm, testing your resolve and the foundation you have built. You must weather the storm to continue.",
  },
  {
    id: 126,
    name: "The Weight of Authority",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Black Onyx",
    plant: "Solomon's Seal",
    incense: "Myrrh",
    mantra: "I wield my growing power with integrity.",
    color: "Jet Black",
    description: "You are granted a measure of authority, and with it, the heavy responsibility to wield it wisely. The temptation to control instead of guide is a subtle trap.",
  },
  {
    id: 127,
    name: "The Dictator's Shadow",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Obsidian",
    plant: "Nightshade",
    incense: "Patchouli",
    mantra: "I confront the tyrant that lives within me.",
    color: "Charcoal",
    description: "In the face of absolute control, you meet your own shadow: the desire to dominate, to enforce, to become the unyielding dictator. This is the crisis of power.",
  },
  {
    id: 128,
    name: "The Crumbling Citadel",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Shungite",
    plant: "Cypress",
    incense: "Vetiver",
    mantra: "I release the need for absolute control.",
    color: "Ash",
    description: "The rigid structures you have built begin to crumble, revealing the prison of your own making. True mastery is not in control, but in surrender to a higher wisdom.",
  },
  {
    id: 129,
    name: "The Architect's Vision",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Fluorite",
    plant: "Ashwagandha",
    incense: "Copal",
    mantra: "I see the blueprint of a more lasting legacy.",
    color: "Indigo",
    description: "From the ruins of the old, a new vision emerges—a legacy built not on force, but on service, wisdom, and the empowerment of others. This is the breakthrough.",
  },
  {
    id: 130,
    name: "The Crystallized Self",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Selenite",
    plant: "Wintergreen",
    incense: "Amber",
    mantra: "I am a clear vessel for timeless wisdom.",
    color: "Ivory",
    description: "Your being crystallizes into a conduit for enduring truth, your authority now flowing from a place of deep inner knowing and clarity. You have become the wisdom you sought.",
  },
  {
    id: 131,
    name: "The Elder's Mantle",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Yellow Sapphire",
    plant: "Tarragon",
    incense: "Sandalwood",
    mantra: "I wear my mastery as a cloak of service.",
    color: "Gold",
    description: "You now wear the mantle of the elder, your life a testament to the mountain path. Your presence alone is a teaching, a guide for those who now begin their own climb.",
  },
  {
    id: 132,
    name: "The Living Legacy",
    gate: 10,
    gateName: "The Master",
    zodiac: "Capricorn",
    element: "Earth",
    planet: "Saturn",
    archetype: "The Master",
    shadow: "The Dictator",
    crystal: "Diamond",
    plant: "Jade Plant",
    incense: "Benzoin",
    mantra: "My greatest work is the world I leave behind.",
    color: "White",
    description: "Your mastery is no longer a personal achievement, but a living legacy woven into the fabric of the world. The mountain has become a part of you, and you a part of its eternal story.",
  },

  // Gate 11: The Sovereign (Aquarius) - Realms 133-144
  {
    id: 133,
    name: "The Unspoken Question",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Angelite",
    plant: "Mugwort",
    incense: "Frankincense",
    mantra: "I listen to the whispers of freedom.",
    color: "Pale Blue",
    description: "A silent question echoes in the soul, a yearning for a reality beyond the known, sparking the first light of cosmic awareness.",
  },
  {
    id: 134,
    name: "The Shattered Mirror",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Labradorite",
    plant: "Gotu Kola",
    incense: "Myrrh",
    mantra: "I see the cracks in my own reflection.",
    color: "Iridescent Silver",
    description: "The illusions of the self begin to fracture, revealing glimpses of a vaster, interconnected consciousness waiting to be discovered.",
  },
  {
    id: 135,
    name: "The Star-Woven Path",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Celestite",
    plant: "Star Anise",
    incense: "Sandalwood",
    mantra: "I walk the path of cosmic design.",
    color: "Celestial Blue",
    description: "The journey into the cosmic blueprint begins, learning to read the patterns of the universe and one's place within them.",
  },
  {
    id: 136,
    name: "The Breath of Liberation",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Aquamarine",
    plant: "Peppermint",
    incense: "Copal",
    mantra: "I breathe in freedom, I exhale chains.",
    color: "Seafoam Green",
    description: "The foundational practice of conscious breath is taught, a tool to dissolve old structures and expand into limitless potential.",
  },
  {
    id: 137,
    name: "The Gravity of Belonging",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Smoky Quartz",
    plant: "Valerian Root",
    incense: "Dragon's Blood",
    mantra: "I release the need for external validation.",
    color: "Deep Gray",
    description: "The pull of old tribes and belief systems challenges the path of the sovereign, a test of the will to stand alone.",
  },
  {
    id: 138,
    name: "The Storm of Innovation",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Larimar",
    plant: "Ginkgo Biloba",
    incense: "Cedarwood",
    mantra: "I embrace the chaos of radical change.",
    color: "Stormy Blue",
    description: "A torrent of disruptive ideas and visions tests the soul's capacity to hold and channel revolutionary energy without breaking.",
  },
  {
    id: 139,
    name: "The Echoes of Exile",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Black Tourmaline",
    plant: "Wormwood",
    incense: "Patchouli",
    mantra: "I embrace the loneliness that births true self.",
    color: "Charcoal",
    description: "The shadow of the Exile emerges, a profound sense of isolation that must be faced to reclaim the power of true individuality.",
  },
  {
    id: 140,
    name: "The Silent Communion",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Amethyst",
    plant: "Lavender",
    incense: "Jasmine",
    mantra: "I find my tribe in the cosmic silence.",
    color: "Royal Purple",
    description: "In the depths of the shadow, a new connection is forged—not with people, but with the universal consciousness itself.",
  },
  {
    id: 141,
    name: "The Quantum Leap",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Moldavite",
    plant: "Blue Lotus",
    incense: "Amber",
    mantra: "I am the architect of my own reality.",
    color: "Electric Green",
    description: "A sudden, electrifying breakthrough shatters all remaining limitations, propelling the soul into a new dimension of being.",
  },
  {
    id: 142,
    name: "The Collective Awakening",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Apophyllite",
    plant: "Calamus",
    incense: "Lotus",
    mantra: "My liberation contributes to the whole.",
    color: "White Gold",
    description: "The personal breakthrough radiates outward, becoming a beacon that contributes to the awakening of the collective consciousness.",
  },
  {
    id: 143,
    name: "The Return to Source",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Selenite",
    plant: "White Sage",
    incense: "Palo Santo",
    mantra: "I am a sovereign being of light.",
    color: "Pure White",
    description: "The journey of sovereignty leads to the understanding that true freedom is the full embodiment of one's divine, original nature.",
  },
  {
    id: 144,
    name: "The Diamond Mind",
    gate: 11,
    gateName: "The Sovereign",
    zodiac: "Aquarius",
    element: "Air",
    planet: "Uranus",
    archetype: "The Sovereign",
    shadow: "The Exile",
    crystal: "Herkimer Diamond",
    plant: "Acacia",
    incense: "Opoponax",
    mantra: "I am the completion of the great cycle.",
    color: "Diamond Light",
    description: "The final realm integrates all lessons into a state of crystalline clarity and unwavering sovereignty, completing the 144 and returning to the One.",
  }

];

export const getRealmById = (id: number): Realm | undefined => {
  return REALMS_DATA.find((realm) => realm.id === id);
};

export const getRealmsByGate = (gate: number): Realm[] => {
  return REALMS_DATA.filter((realm) => realm.gate === gate);
};

export const getRealmsByElement = (element: string): Realm[] => {
  return REALMS_DATA.filter((realm) => realm.element === element);
};

export const getRealmsByZodiac = (zodiac: string): Realm[] => {
  return REALMS_DATA.filter((realm) => realm.zodiac === zodiac);
};
